register new user
atlp-rwanda/Avengers-Phantom-BE pull request #44
Opened 2022-06-20 14:08 UTC by kareraolivier

### what does pr do
Register new users in documentation

### How to use it
Check the process of adding new user 

### How to run It
You can use "npm run start:dev"
check this link "localhost:{port}/documentation"

2022-06-20 14:13 UTC, un-anelka approved these changes

2022-06-20 14:43 UTC, Gedeonir approved these changes

2022-06-23 08:00 UTC, Anguandia commented
Good work, @kareraolivier next time, please give a better PR description. This [guide](https://github.com/atlp-rwanda/engineering-playbook/tree/master/5.%20Developing/Conventions#branch-naming) will always be a good starting point for best practices

2022-06-23 08:09 UTC, Anguandia requested changes
Good work, @kareraolivier please address these concerns:
- give a better PR description. This [guide](https://github.com/atlp-rwanda/engineering-playbook/tree/master/5.%20Developing/Conventions#branch-naming) will always be a good starting point for best practices
- the PR title , "register new user" sound like a feature, please get appropriate titles for your PRs
- this is not a feature, it is a chore. The branch naming ft-documentation is wrong, please rename it. The name should also include the feature you are documenting. Please refer to the guide above

2022-07-06 17:09 UTC, mansurissa approved these changes

2022-07-06 17:09 UTC, merged