ft(upload-imges): Configure cloudinary
atlp-rwanda/Avengers-Phantom-BE pull request #48
Opened 2022-06-24 14:10 UTC by abraham-kwizera

## What does this PR do?

> Update Profile Picture & Configure Cloudinary

## Description of Task to be completed?

- [x] Update Users model with profilePicture field
- [x] update seeders
- [x] install cloudinary package
- [x] Update the updateProfile route with profilePicture field for holding images
- [x] Implements setups in update profile endpoint, of the upload presets to where images will be located
- [x] Retouch on sequelize instance
- [x] Remove conflicts referring to base branch, that has resulted in sequelize instance error

### How should this be manually tested?

step1: clone git repo if not yet done
step2: `cd Avengers-Phantom-BE`
step3: `npm i` or `npm install` to install dependencies
step4: `npm run start:dev` to start the server

#### API

{{URL}}api/v1/users/updateProfile/:uuid

[POSTMAN](https://www.postman.com/) to test all the above APIs

2022-06-26 08:34 UTC, capitale250 requested changes
and also we have two files in migration wich serves the same role

2022-06-26 08:34 UTC, capitale250 commented on migrations/20220429162252-create-user.js
> +      isAssigned: {
we have two isassigned columns and also rolename and others

2022-06-27 08:24 UTC, Gedeonir requested changes
- Changing the response messages will cause the tests written before to fail. try to not change it especialy on roles,buses,and authentication files.

- we are no longer using config.json because it exposes database info we are using config.js file and save info in .env file and failing to do so it will make our CIs to fail.
- again to folder structure has changed we no longer have tests stored in test folder instead every test is in its corresponding folder(ex: test file for roles is in Role folder)
- do well your rebase just pull develop to get latest content. some files still has content of from the last month whereas they are changed now like phantom.yml in github/workflows
-

2022-06-27 10:50 UTC, un-anelka reviewed
Just do rebase on the current changes on the develop to have updated project structure and try to use config.js instead of config.json file and finally do squash your commits.

2022-06-30 09:25 UTC, abraham-kwizera commented on migrations/20220429162252-create-user.js
> +      isAssigned: {
Well noted. Solved.

2022-07-06 17:11 UTC, closed without merging